# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

AS=/usr/bin/gcc
MM=/usr/bin/gcc
CU=/usr/bin/clang
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
MXX=/usr/bin/gcc

LD=/usr/bin/g++
SH=/usr/bin/g++
AR=/usr/bin/ar

Granit_LD=/usr/bin/g++
Granit_CXX=/usr/bin/gcc
Granit_CXX=/usr/bin/gcc

Granit_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -isystem /home/nydus/.xmake/packages/a/asio/1.30.2/c1047cd667c14a44bea718715a77a7f5/include -DNDEBUG
Granit_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -isystem /home/nydus/.xmake/packages/a/asio/1.30.2/c1047cd667c14a44bea718715a77a7f5/include -DNDEBUG
Granit_LDFLAGS=-m64 -s

default:  Granit

all:  Granit

.PHONY: default all  Granit

Granit: build/linux/x86_64/release/Granit
build/linux/x86_64/release/Granit: build/.objs/Granit/linux/x86_64/release/src/main.cpp.o
	@echo linking.release Granit
	@mkdir -p build/linux/x86_64/release
	$(VV)$(Granit_LD) -o build/linux/x86_64/release/Granit build/.objs/Granit/linux/x86_64/release/src/main.cpp.o $(Granit_LDFLAGS)

build/.objs/Granit/linux/x86_64/release/src/main.cpp.o: server
	@echo compiling.release src/main.cpp
	@mkdir -p build/.objs/Granit/linux/x86_64/release/src
	$(VV)$(Granit_CXX) -c $(Granit_CXXFLAGS) -o build/.objs/Granit/linux/x86_64/release/src/main.cpp.o src/main.cpp

clean:  clean_Granit

clean_Granit: 
	@rm -rf build/linux/x86_64/release/Granit
	@rm -rf build/linux/x86_64/release/Granit.sym
	@rm -rf build/.objs/Granit/linux/x86_64/release/src/main.cpp.o

