add_rules("mode.debug", "mode.release")
add_requires("asio", "nlohmann_json")
set_languages("cxx23")
target("Server")
    set_kind("binary")
    add_files("server/*.cpp")
    add_packages("asio", "nlohmann_json")
target("Client")
    set_kind("binary")
    add_files("client/*.cpp")
    add_packages("asio")