-- add_rules("mode.debug")
add_rules("mode.release")
set_languages("cxx23")
-- set_policy("build.sanitizer.address", true)
-- set_policy("build.sanitizer.thread", true)
-- set_policy("build.sanitizer.memory", true)
-- set_policy("build.sanitizer.leak", true)
-- set_policy("build.sanitizer.undefined", true)

add_requires("rpclib", "nlohmann_json", "openssl3", "cpp-httplib", "implot")
add_requires("imgui", {configs = {glfw = true, opengl3 = true}})
target("Encryptor")
    set_kind("static")
    add_files("lib/*.cpp")
    add_packages("openssl3", "rpclib", "nlohmann_json", "cpp-httplib")
target("Server")
    set_kind("binary")
    add_files("server/*.cpp")
    add_packages("rpclib", "nlohmann_json", "openssl3", "imgui", "cpp-httplib", "implot")
target("Client")
    set_kind("binary")
    add_files("client/*.cpp")
    add_packages("rpclib", "nlohmann_json", "openssl3", "cpp-httplib")
